"""initial

Revision ID: 69ea34827672
Revises: 
Create Date: 2026-01-19 23:05:44.816877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ea34827672'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_currency',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('eurpln', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('usdpln', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_currency')
    # ### end Alembic commands ###
