"""initial

Revision ID: 75e20962b1b0
Revises: 1be592a7f003
Create Date: 2026-01-22 00:26:18.566478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e20962b1b0'
down_revision: Union[str, Sequence[str], None] = '1be592a7f003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_forecast',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('eurpln_pred', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('plneur_pred', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('predictions_eurpln',
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.Column('predicted_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('mae', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('r2', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('target_date')
    )
    op.create_table('predictions_plneur',
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.Column('predicted_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('mae', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('r2', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('target_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions_plneur')
    op.drop_table('predictions_eurpln')
    op.drop_table('currency_forecast')
    # ### end Alembic commands ###
